### ISSUE TITLE
ETQ visiteur, j'ai besoin d'accéder facilement aux pages principales du site web et 

### ISSUE THREAD

**Issue by Volubyl** [MJ-Conseil/mathieujahnich#30]
# Description du besoin

ETQ visiteur, j'ai besoin d'accéder facilement aux pages principales du site web et j'aimerais le faire à l'aide d'un menu

Voir maquette : https://www.figma.com/file/Vum0BnvOCMLBkBHCnTPyzc/Site-Mathieu-Jahnich?node-id=9%3A125&t=okWm8DcpEsxOavQN-0

# Critères d'acceptation

- [ ] je peux utiliser le menu pour naviguer à la souris entre les pages principales du sit web
- [ ] je peux naviguer au clavier dans la menu
- [ ] je peux navigueur aussi bien en mode mobile qu'en mode desktop
- [ ] en mode mobile, le menu s'ouvre en cliquant sur l'icone
- [ ] en mobile, quand le menu de navigation est ouvert, celui-ci doit recouvrir entièrement l'écran
- [ ] en desktop, le menu doit rester en haut quand je scroll la page (@AnneFa tu confirmes ?)

# Conidérations techniques et d'accessibilité

Pour la réalisation de ce menu, il y a deux pattern aria dont l'on pourrait s'inspirer

- Pour la vue mobile : https://www.w3.org/WAI/ARIA/apg/patterns/dialogmodal/
- Pour le menu desktop :https://www.w3.org/WAI/ARIA/apg/patterns/menu/

## Respect des landmarks

Le menu doit obligatoirement être inclus dans une balise `nav` et être incluse dans le `header` de la page

## Respect de l'"ARIA Authoring Practices Guide" décrit par le W3C

L'APG possède un [guide](https://www.w3.org/WAI/ARIA/apg/patterns/menu/) pour réaliser un menu accessible. Je pense qu'il serait pas mal de le respecter

# Sources d'inspiration

- Le header du DSFR https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/en-tete
