### ISSUE TITLE
ETQ visiteur je souhaite voir une landing page en arrivant sur le site

### ISSUE THREAD

**Issue by Volubyl** [MJ-Conseil/mathieujahnich#31]
# Description du besoin

La landing page est la page sur laquelle l'on arrive sur le site web. 

Elle est composée des élements suivants :

- un header comprenant le logo et la navigation principale ( Issue #30 )
- une zone principale qui sert d'accroche ( PR: #36 )
- une zone signes particuliers ( PR: #45 )
- une zone offres et services ( PR: #40 )
- une zone "à la une du blog" qui présente les articles de blog mis en avant
- un footer 

# Critères d'acceptation

- [ ] en arrivant sur le site web j'arrive sur cete page
- [ ] en arrivant  sur le site, je peux voir le header avec la navigation
- [ ] en arrivant sur le site, je peux voir la section signes particuliers
- [ ] en arrivant sur le site, je peux voir la section offre de service
- [ ] en arrivant sur le site je peux voir les articles du blog mis en avant
- [ ] en arrivant sur le site, je peux voir le footer

### Critères d'éco-conception et acessibilité

- [ ] cette page à un éco index faible
- [ ] cette page est accessible au sens RGAA du terme
- [ ] il est possible de navigueur au clavier sur cette page
- [ ] la page est découpée en section (header, main, footer, ...) de manière logique et sémantique

# Considérations techniques

### Mobile first ?

Etant donné que cette page doit fonctionner aussi bien en mobile qu'en deskop est-ce qu'il serait bien de l'intégrer en mobile firtst ?

### Présentation du contenu sous forme de `card`

Beaucoup de contenu sur cette page est présenté sous la forme de "Carte"

Pour que ce composant soit accessible l'on peut s'inspirer de https://inclusive-components.design/cards/

La stratégie "The pseudo-content trick" pourrait être une bonne piste pour éviter d'avoir un 'a' qui entoure toute la carte

### Retours UI

- [ ] Menu : Typo sur le mot "Accueil" (écrit "Acceuil")
- [ ]En-tête : logo à droite en contour blanc au lieu de blanc plein avec opacité faible. --> Besoin que je fournisse un fichier SVG ?
- [ ] En-tête : MJ conseil doit être en couleur orange de la charte soit en RGB : 243, 196, 97
- [ ] En-tête : ajouter une marge bottom sous le paragraphe et une marge top au dessus du titre "Signes particuliers"
- [ ] Marge : j'ai lu qu'il y avait un problème d'affichage et je suis sur Mac 15 pouces et Firefox mais il faudrait des marges de 180 px minimum
- [ ]  Signes particuliers : prévoir un espace de 3,5 rem entre le titre et les cartes
- [ ]  Prendre de la hauteur : le logo a un petit plein bizarre. Je vais vérifier le svg.
- [ ] Paragraphes : plusieurs textes font 16 px seulement. Dans les maquettes ils font tous généralement 18 px minimum soit 1,2 à 1,4 rem.
- [ ]  Actus : manque encore le bouton et son effet de survol
- [ ] Conception et création : Je n'interviens pas au nom de Designers Ethiques donc je veux bien qu'on mette "Anne Faubry" au lieu de "Designers Ethiques". :) Merci !
